name: test-and-build

on:
  push: {}

permissions:
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:b9f575d8d3b13c7f4ce3431438ad925ce5e1e85adb92bd7357138945aa6a7243
      env:
        CGO_ENABLED: 1
        GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Required Packages
        run: |
          apt-get install \
            -y --no-install-recommends \
            libhidapi-dev \
            libudev-dev

      - name: Test and Lint
        run: |
          go test -v ./...
          golangci-lint run ./...

      - name: Build release
        run: go build .
