name: test-and-build

on:
  push: {}

permissions:
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:4f5382f4d8a5d0f7e109258b86200f2cc6e9fb76758ed4c8c404a1e8df4b68ea
      env:
        CGO_ENABLED: 1
        GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Required Packages
        run: |
          apt-get install \
            -y --no-install-recommends \
            libhidapi-dev \
            libudev-dev

      - name: Test and Lint
        run: |
          go test -v ./...
          golangci-lint run ./...

      - name: Build release
        run: go build .
