name: test-and-build

on:
  push: {}

permissions:
  contents: read

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:4a53384eefc0e7564a3c56d345250a4648b679ef0e53b7b1931a1c1d99db4342
      env:
        CGO_ENABLED: 1
        GOPATH: /go

    runs-on: forgejo

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Required Packages
        run: |
          apt-get install \
            -y --no-install-recommends \
            libhidapi-dev \
            libudev-dev

      - name: Test and Lint
        run: |
          go test -v ./...
          golangci-lint run ./...

      - name: Build release
        run: go build .
